import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/header/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/eaa4cih.css" />
      </head>
      <body className="font-proxima-nova antialiased">
        <Nav className='max-w-8xl mx-auto'/>
        {children}
      </body>
    </html>
  );
}
